version: "3.7"

services:

  # normalization:
  #   container_name: normalization
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./docker/normalization/Dockerfile
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - redis
  #     - mongo
  #   env_file:
  #     - .env

  mongo:
    container_name: product_collector_mongo
    build:
      context: ./
      dockerfile: ./docker/mongo/Dockerfile
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - product_collector_mongo:/data/mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: pc-user
      MONGO_INITDB_ROOT_PASSWORD: pc-password
      MONGO_INITDB_DATABASE: product-collector
    ports:
      - 27027:27017

  backend:
    container_name: product_collector_backend
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: /bin/sh -c "npm install && npm run dev"
    ports:
      - 3001:3000
    depends_on:
      - mongo

volumes:
  product_collector_mongo:
  product_collector_redis: